name: Hans Logren
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68158
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4b1bc'
    - '#847e88'
    - '#3c373d'
    - '#020202'
    - '#f4d9c6'
  brandStrength: 1
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
