name: Hans Logren
favicon: null
layout_spectrum: 0.32447
typography_spectrum: 0.39186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969197'
    - '#020001'
    - '#ebdcd7'
    - '#544943'
    - '#7b7610'
  brandStrength: 0.875
  lightness: 0.0625
  saturation: 0.08669539610855281
  rhythmicContrast: 0.2264412073418498
purpose: []
